# Prettier configuration for TypeScript and JavaScript
printWidth: 80              # Maximum line length
tabWidth: 2                # Number of spaces per indentation level
useTabs: false             # Use spaces instead of tabs
semi: true                 # Add semicolons at the end of statements
singleQuote: true          # Use single quotes instead of double quotes
quoteProps: as-needed      # Quote object properties only when necessary
trailingComma: es5         # Add trailing commas where valid in ES5 (objects, arrays)
bracketSpacing: true       # Add spaces between brackets in object literals
arrowParens: always        # Always include parentheses around arrow function arguments
bracketSameLine: false     # Put closing > of HTML/JSX on a new line