export * from './scope.js'
export * from './allFuncs.js'
// std lib
export * from './types/SuperPromise.js'
export * from './types/SuperNumber.js'
export * from './types/SuperString.js'
export * from './types/SuperBoolean.js'
export * from './types/SuperStruct.js'
export * from './types/SuperArray.js'
export * from './types/SuperFunc.js'
